### ISSUE TITLE
Reading CSV/Parquet files written by Spark Job from Pandas

### ISSUE THREAD

**Issue by brookewenig** [databricks/koalas#111]
I realize this is a Pandas issue, but it will impact folks who want to switch between pandas and koalas/Spark.

If you write a spark file out (e.g. CSV or Parquet), you cannot read it in from Pandas (you can read it in the individual files though).

A lot of folks have complained about this in various places:
https://github.com/dask/fastparquet/issues/159
https://github.com/uber/petastorm/issues/321

Would be awesome if we had a workaround.

**Comment by rxin** [comment]
Can you paste an example file and exception?

**Comment by thunterdb** [comment]
From seeing the tickets, it looks like the workaround downstream will be an upgrade of the parquet reador or pandas.

**Comment by ch-nickgustafson** [comment]
This could be because when writing a parquet with Spark, several non parquet files are produced. e.g.
```bash
/path/to/data/my_data.parquet/_SUCCESS
/path/to/data/my_data.parquet/_committed_12345678
/path/to/data/my_data.parquet/_started_12345678
/path/to/data/my_data.parquet/_part-00000-98178901734kjalksjd.snappy.parquet
```

The workaround/kludge I've used if I want to then read these parquet output using pandas is to copy all of the `*.parquet` files to a new directory. You should then be able to read the parquet files with pandas.
