### ISSUE TITLE
Basic functionalities to support

### ISSUE THREAD

**Issue by rxin** [databricks/koalas#124]
I quickly went through Pandas and Spark DataFrame docs and came up with a list of basic functions to add:

The following is a list of methods that we should make available in koalas.DataFrame and koalas.Series.

(In general, ignore "axis" argument for now, and assume axis = 0, i.e. row wise)

koalas.DataFrame/Series:

- to_pandas
- spark_schema
- select
- selectExpr

- describe
- dtypes
- explain
- head

- agg
- aggregate
- groupby

- isna
- dropna
- fillna
- notna

- abs
- all
- any
- max
- min
- mean
- kurt
- std
- skew
- sum
- var

- sub
- add
- mul
- div
- mod
- floordiv
- pow
- lt
- gt
- le
- ge
- ne
- eq

- append
- replace

- sample
- sort_values (done in #204)
- sort_index
- nlargest (#302)
- nsmallest (#302)

koalas.Series:

- unique  -> koalas.DataFrame
- nunique  -> same as Pandas
- is_unique
- value_counts

- str.upper
- str.lower
- str ...

koalas.DataFrame:

- append
- join
- merge

**Comment by HyukjinKwon** [comment]
@rxin, we have implemented everything except two:

- select
- selectExpr

*`spark_schema` is partially implemented at Series instead as `spark_type`.

For `select`, it conflicts with [pandas' `select`](https://pandas.pydata.org/pandas-docs/version/0.23.4/generated/pandas.DataFrame.select.html) so it might be better to don't implement for now.

`selectExpr` case is a bit arguable too because we have the external and internal column names are different. For example, the column name can be a tuple `("a", "b", "c")`; however, that's not allowed in Spark side.

Let me close this one for now but let me know if you have a different thought.
