### ISSUE TITLE
read_sql_query / read_spark_io on mssql trigger toPandas

### ISSUE THREAD

**Issue by Harshitg** [databricks/koalas#1365]
While executing koalas, i am continuously getting triggers to toPandas usage in 

```
exposure_data_original = ks.read_sql_query(exposure_query, conn)  
dataframe = ks.read_spark_io(dbtable = 'Position_Facility_ExposureData', format='JDBC',url = conn, index_col='date', fetchsize = 10000)
```
![image](https://user-images.githubusercontent.com/1675591/77529247-40971300-6eb5-11ea-9a50-035256f1e4e0.png)

![image](https://user-images.githubusercontent.com/1675591/77529279-50165c00-6eb5-11ea-8fd0-d18c0b278bb8.png)

Any idea what's going wrong here

**Comment by HyukjinKwon** [comment]
Are you able to make it working by purely using PySpark, and what exception message did you have?

**Comment by Harshitg** [comment]
Oh yes, on PySpark per say there is no issue. My mistake to not be clear, i had a question around is there a reason toPandas is getting triggered?

**Comment by HyukjinKwon** [comment]
Do you mind sharing the exception message you had?

**Comment by Harshitg** [comment]
While executing:
```

dataframe = ks.read_spark_io(dbtable = 'Position_Facility_ExposureData', format='JDBC',url = conn, index_col='date', fetchsize = 10000)
dataframe.head(100)
```
I am reading the kdF dataframe, however the internals are converting it into pdf

```
  File "C:\Users\HarshitGupta\AppData\Roaming\Python\Python37\site-packages\databricks\koalas\internal.py", line 799, in pandas_df
    pdf = sdf.toPandas()
```

**Comment by HyukjinKwon** [comment]
1. about `toPandas`, I think it's being called when it's rendered at your shell or notebook. If you don't print out, it won't collect the data. For example, try to set your final results into a variable and don't print out.

2. That exchange will probably be because of default index. See https://koalas.readthedocs.io/en/latest/user_guide/best_practices.html#use-distributed-or-distributed-sequence-default-index and https://koalas.readthedocs.io/en/latest/user_guide/best_practices.html#specify-the-index-column-in-conversion-from-spark-dataframe-to-koalas-dataframe

**Comment by Harshitg** [comment]
1. Thanks for clarification, i can confirm it is happening while rendering.
2. I will check.

Closing for now
