### ISSUE TITLE
df.cache() question

### ISSUE THREAD

**Issue by Harshitg** [databricks/koalas#1373]
PySpark allows for giving an argument for caching type. How can we pass this in Koalas?

Spark 
```
>>> df.persist(pyspark.StorageLevel.MEMORY_ONLY)
DataFrame[id: bigint, name: string]

>>> df.persist(pyspark.StorageLevel.DISK_ONLY)
DataFrame[id: bigint, name: string]
```

**Comment by itholic** [comment]
Happy to see you @Harshitg , Thanks for reporting an issue for Koalas :D

Since Koalas is supporting cache as a `cache()` of PySpark under-the-hood, we can't specify the storage level for now. (It uses `MEMORY_ONLY` by default) 

https://github.com/databricks/koalas/blob/fd60bfed206a1aef3e57a08356536fad9a3d7281/databricks/koalas/frame.py#L10025-L10027

For specifying the storage level (as you said, the 'caching type'), we should change the `cache()` to `persist()` for adding proper parameter which can accept the storage level.

@HyukjinKwon @ueshin What do you think about changing our caching mechanism from `cache()` to `persist()` for that users can specify the storage level by parameter??

**Comment by ueshin** [comment]
As PySpark has both `cache()` and `persist()`, we can just add `persist()` method the same as PySpark.
Btw, the default value is `MEMORY_AND_DISK` instead of `MEMORY_ONLY`.

Also it might be good if `_CachedDataFrame` has `storage_level` property for users to check the current storage level.

@itholic Do you want to submit the PR?

**Comment by itholic** [comment]
@ueshin 

> Btw, the default value is MEMORY_AND_DISK instead of MEMORY_ONLY.

Thanks for the comment and fixing the mistake!

Sure, I'll add the `DataFrame.persist()` soon.

@Harshitg I'll try to make the `DataFrame.persist()` method until next release so that you can use the caching type after then. 😸

**Comment by Harshitg** [comment]
@itholic Thanks for the prompt response.

**Comment by itholic** [comment]
@Harshitg My pleasure :D
