### ISSUE TITLE
Koalas DataFrame should only have Pandas corresponding APIs (not Spark APIs)

### ISSUE THREAD

**Issue by HyukjinKwon** [databricks/koalas#139]
This is partially of https://github.com/databricks/koalas/issues/119

I was thinking Koalas DataFrame strictly should have Pandas corresponding APIs, although there might be few exceptions with some strong reasons.

Meaning Koalas DataFrame should not have Spark DataFrame specific APIs like `explain()` or `selectExpr()`. My current thought is we have a API like `koalas_df.to_spark()` (borrowed from @ueshin's idea via offline discussion) so that users can use Spark APIs.

**Koalas API usages**

```python
koalas_df.loc(...)
koalas_df.drop(...)  # works as Pandas API
```

**Spark API usages**

```python
koalas_df.to_spark().explain()
koalas_df.to_spark().selectExpr()
koalas_df.to_spark().drop(...)  # works as Spark API
```

This can clearly define what Koalas APIs expect and Spark APIs expect.

**Comment by thunterdb** [comment]
I think that users should be able to pick what they need, in particular things like .cache() or .repartition() which can be necessary. Doing `koala_df.to_spark().cache().to_koalas()` looses the index and metadata, so it is a no-go. Other users should also chime in though.

**Comment by ueshin** [comment]
I'd prefer to separate API.
Since pandas has the same name functions as Spark, even the primitive ones, `select`, `filter/where`, then users can't pick the preferable one and will be confused by the APIs from the different origin.
Also what if pandas adds the same name function in the future?

I'd propose `spark` property which handles Spark APIs but try to preserve indexes as far as possible:

```
kdf.select(...)  # works as the same as pandas dataframe
kdf.spark.select(...)  # works as similar to spark dataframe but preserves index as far as possible, and return koalas dataframe
kdf.to_spark().select(...)  # drops out from Koalas, returns spark dataframe and select on it
```

**Comment by HyukjinKwon** [comment]
Yes, I agree with @ueshin. If there's no choice, then I think https://github.com/databricks/koalas/issues/139#issuecomment-485728893 is the last resort.

But I was thinking the goal of this project is to let Pandas users can directly be able to use PySpark without any efforts. Since the targeted users are Pandas users, they might not use PySpark's APIs quite often.

**Comment by thunterdb** [comment]
I agree that we should not put everything. That being said, some of them are very helpful, simply because they do not have any equivalent in pandas and are very common in spark. Here is how we can start:

Unscoped (directly in `DataFrame` or `Series`):
 - `select` and `selectExpr`. This is very useful for quickly building expressions, and pandas has even a dialect for doing that. We should have a separate thread about how much we accept here.
 - very common functions like `alias`, `join`

Unscoped or scoped (no particular preference here). Expected to return a Koalas dataframe:
 - SQL-related: `crossJoin`, `crosstab`, `hint` etc.
 - understanding the underlying representation: `printschema`, `schema`
 - specify the memory layout (at least the core functions): `cache`, `repartition`

Scoped or only available through conversion with `.toDF()`. Expected to return a `scalar`, `Series`, `pd.DataFrame` or `spark.DataFrame`
 - streaming-related: `withWatermark`, `isStreaming`
 - big-data related: `approxquantiles` -> should actually return a `pd.Series` and should probably be scoped then.

**Comment by HyukjinKwon** [comment]
@thunterdb, how about we start from: Koalas to have Pandas corresponding APIs only and provide an API like `to_spark()` first? I think this will be the subset of https://github.com/databricks/koalas/issues/139#issuecomment-485728893 and/or https://github.com/databricks/koalas/issues/139#issuecomment-485789617 anyway later.

a) this way is pretty clear to dev and users as the starting point too. b) we can decide which way is better later, and can adopt the actual user's expectation later easily

**Comment by HyukjinKwon** [comment]
cc @rxin too to collect more feedback.

**Comment by rxin** [comment]
This is a tough one -- to be honest I think we can pick something safer, and try to use this more, get feedback, and then it might become more obvious what we should do.

**Comment by rxin** [comment]
Closing this as it will be part of the design philosophy doc.
