### ISSUE TITLE
Document that we don't support the compatibility with non-Koalas APIs yet.

### ISSUE THREAD

**Issue by HyukjinKwon** [databricks/koalas#1414]
Seems like people want to convert their codes directly from pandas to Koalas. One case I often observe is, they want to convert the codes that works together with other Python standard functions such as `max`, `min`, or list/generator comprehensions, e.g.)

```python
import pandas as pd
data = []
for a in pd.Series([1, 2, 3]):
    data.append(a)

pd.DataFrame(data)
```

In Koalas, such example does not work. We should preemptively document and guide users to stick to Koalas APIs only.

**Comment by HyukjinKwon** [comment]
@beobest2 would you be interested in this?

**Comment by beobest2** [comment]
@HyukjinKwon Sure, let me try. thank you

**Comment by beobest2** [comment]
@HyukjinKwon 
I have written the document below, does this match your intentions? 
If not, please understand my lack of understanding.

===
FAQ

[Can I use the code used for Pandas as is?]

Replacing the Pandas module with Koalas works fine for most.
However, some compatibility with non-Kalas APIs is not yet supported.
Koalas cannot be used with other Python standard functions like `max`, `min` and `sum` or `list / generator comprehensions`.

Therefore, for the same operation, it should be changed as below:

- If you want to get `max`, `min`, and `sum` values, 
you can use the functions provided by Koalas instead of the Python standard functions.

```python
>>> max(pd.Series([1, 2, 3]))
3
>>> min(pd.Series([1, 2, 3]))
1
>>> sum(pd.Series([1, 2, 3]))
6
>>>
>>> ks.Series([1, 2, 3]).max()
3
>>> ks.Series([1, 2, 3]).min()
1
>>> ks.Series([1, 2, 3]).sum()
6
```

- If you want to use `list / generator comprehensions`, you can use Numpy object with `to_numpy()`.

```python
>>> import pandas as pd
>>> import databricks.koalas as ks
>>>
>>> data = []
>>> for a in pd.Series([1, 2, 3]):
...     data.append(a)
...
>>> for a in ks.Series([4, 5, 6]).to_numpy():
...     data.append(a)
...
>>> data
[1, 2, 3, 4, 5, 6]
```

===

PS. I am not sure where to include the guide documentation. (Whether to add to the "FAQ" or separately to the "User Guide")

**Comment by HyukjinKwon** [comment]
I think we should better move them to Best Practice. I think we could rephrase, for example as below. Feel free to reword or rephrase.

Title: Use Koalas APIs directly whenever possible

Contents:
While Koalas has similar APIs with pandas, some APIs are not explicitly supported. For example, Python built-in functions such as `min`, `max`, etc. require the given argument to be iterrable. Koalas does not implement `__iter__()` yet to prevent users to collect all data into the client (driver) side from the cluster. See the example below:

```python
>>> import pandas as pd
>>> max(pd.Series([1, 2, 3]))
3
>>> min(pd.Series([1, 2, 3]))
1
>>> sum(pd.Series([1, 2, 3]))
6
```

pandas dataset live in the local, iterable ... blah blah ...

```python
>>> import databricks.koalas as ks
>>> ks.Series([1, 2, 3]).max()
3
>>> ks.Series([1, 2, 3]).min()
1
>>> ks.Series([1, 2, 3]).sum()
6
```

Koalas performes it in a distributed manner.. blah blah

... Another common pattern from pandas users is to rely on list or generator comprehensions ...:

```python
>>> import pandas as pd
>>> data = []
>>> pser = pd.Series([1, 2, 3])
>>> for v in pser:
...     data.append(v + 1)
>>> pd.Series(data)
```

In Koalas, you can do it via:

```python
>>> import databricks.koalas as ks
>>> kser = ks.Series([1, 2, 3])
>>> kser + 1  # or kser.apply example? or kdf.map_in_pandas example? 
```

In case of NumPy universial functions, they are supported and can be naturally used in most cases. -> it was added https://github.com/databricks/koalas/pull/1096 https://github.com/databricks/koalas/pull/1106 https://github.com/databricks/koalas/pull/1128 FYI

**Comment by HyukjinKwon** [comment]
You can open a PR and we can iterate the review for better trackability.

**Comment by beobest2** [comment]
okay~ I'll open a PR. thank you
