### ISSUE TITLE
DataFrame.droplevel

### ISSUE THREAD

**Issue by ueshin** [databricks/koalas#1614]
Implement `DataFrame.droplevel`.

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.droplevel.html

**Comment by jijosg** [comment]
I would like to work on this.

**Comment by itholic** [comment]
@jijosg Let's go! :D

**Comment by jijosg** [comment]
Since i am a newbie to this, please let me know if this question is not relevant.
The original implementation of droplevel refers to _get_axis(axis) method to get the level names, are we supposed to implement that method as well? I couldnt find the existing implementation of such a function. @itholic  if you could guide me forward that would be helpful. 
Thanks

**Comment by itholic** [comment]
Hi, @jijosg .
I don't think we have to necessarily implement `_get_axis` for now.
Just feel free to implement method whatever you want, and I'll review it for you after then :D
