### ISSUE TITLE
Series Boxplot

### ISSUE THREAD

**Issue by Noam2710** [databricks/koalas#1827]
Hey, in the Series Boxplot you show the top 1k absolute values.
However, may be some values which are fliers but don't have a big absolute value.
In my opinion, you should take the absolute value of the **difference**.

https://github.com/databricks/koalas/blob/b0e1c41389cd5ec09858cbf2a2f94ea38672a1bb/databricks/koalas/plot.py#L479-L492

I will illustrate another issue by a screen shot -

![image](https://user-images.githubusercontent.com/26877695/95206789-c9412500-07ef-11eb-8b4e-150da9df6f1c.png)

Thanks a lot :)

**Comment by ueshin** [comment]
cc @HyukjinKwon

**Comment by HyukjinKwon** [comment]
@dvgodoy, sorry maybe dumb question. Why do we make the fliers as absolute values? I thought that we should keep their sign as is so they can be shown as proper outliners whether it is positive or negative but now it looks like they are all converted to positive absolute values? Reading the comment at https://github.com/databricks/koalas/pull/294#issuecomment-491607026, looks it was intentional.

@Noam2710, the absolute value of the difference sounds making sense. Would you mind opening a PR and going ahead?

**Comment by dvgodoy** [comment]
@HyukjinKwon you and @Noam2710 are absolutely right - it was a silly mistake on my part when I implemented this. I got so concerned about limiting the number of fliers that I ended up introducing this error.

**Comment by HyukjinKwon** [comment]
@dvgodoy would you mind opening a PR to fix this when you find some time?

**Comment by HyukjinKwon** [comment]
@dvgodoy, thanks for confirmation. Would you mind opening a PR to fix this when you find some time?
