### ISSUE TITLE
Type hints do not works for many spark types

### ISSUE THREAD

**Issue by vkrot-exos** [databricks/koalas#1840]
Type hints do not support float type and many others.
Sample code that does not work:
```
    import databricks.koalas as ks
    import pandas as pd

    df = spark_session.createDataFrame([
        (1, 1.,),
    ], 'a long, b float')
    kdf = df.to_koalas()

    def f(pdf: pd.DataFrame) -> ks.DataFrame[zip(kdf.columns, kdf.dtypes)]:
        return pdf

    print(kdf.koalas.apply_batch(f))
```

It throws error:
```
TypeError: Type <class 'numpy.float32'> was not understood.
from databricks/koalas/typedef/typehints.py:128
```

Changing `b` column type from `float` to `double` fixes this error
`strinng` columns are also not supported in this scenario

**Comment by vkrot-exos** [comment]
temporary workaround I'm using:
```
def fixed_types(dtypes):
    def mapping(t):
        import numpy as np
        if t == np.float32:
            return float
        if t == np.object:
            return str
        if t == np.bool_:
            return bool
        return t
    return [mapping(t) for t in dtypes]
def func(df) -> ks.DataFrame[zip(kdf.columns, fixed_types(kdf.dtypes.values))]:
```

I can create a PR, but is it safe always to assume `np.object` can be substituted by `str`?

**Comment by ueshin** [comment]
Sounds like we are missing some of the type mapping. I guess we can handle it in `as_spark_type` ([typehints.py#L90-L128](https://github.com/databricks/koalas/blob/master/databricks/koalas/typedef/typehints.py#L90-L128)).

For `np.object`, I'm afraid we shouldn't assume it's `str` since date type or bool type including nans or some more data types could also be `np.object`.

Would you mind submitting the PR? We can discuss more there.

Thanks!

**Comment by itholic** [comment]
Let me take a look at this one
