### ISSUE TITLE
Implement missing functions for 10-minute tutorial with Koalas

### ISSUE THREAD

**Issue by garawalid** [databricks/koalas#382]
This is the list of missing functions for **10-minute tutorial with Koalas** (#196) 

+ [ ] DataFrame.pivot_table
+ [ ] DataFrame.reindex
+ [ ] DataFrame.apply
+ [x] DataFrame.append (#388)
+ [x] DataFrame.at (#384)
+ [ ] DataFrame.T
+ [x] DataFrame.sub (#427)

Ignored functions
+ DataFrame.to_hdf
+ DataFrame.iat
+ DataFrame.shift

Some functions could be implemented for both DataFrame and Series. 

For contributors, please mention that you're working on some functions here and go ahead.

**Comment by garawalid** [comment]
@HyukjinKwon any thoughts?

**Comment by thunterdb** [comment]
Let's focus on: pivot_table, reindex, apply, append, at, T, to_hdf (in this order)

The other functions have big performance impact and will require more careful integration with spark, by using window functions under the hood for example.

@garawalid, if you are looking at implementing some of them, I suggest that we go in this order. What are your thoughts?

**Comment by floscha** [comment]
I can definitely start with `reindex`,  `append` and `at` as those three all seem pretty straight forward.

The others seem tricky to me for different reasons:
- `pivot_table` and `T` might require special care with their implementation as they potentially move around huge amounts of data between workers.
- `apply` should probably take UDFs since pandas/NumPy methods need to move the data from the Spark process to the Python process and back. Expecting the user to use PySpark UDFs however, would (again) break the separation between the (Py)Spark and pandas APIs.
- `to_hdf` should be easy to implement but requires a decision if the write to disk should happen from Spark or from Python.

**Comment by rxin** [comment]
Does anybody still use hdf these days? Maybe I'm not familiar enough with the pandas use cases. I feel maybe it's ok to skip hdf given people rarely use that in "big data".

**Comment by athena15** [comment]
@rxin, FWIW I think you are right that to_hdf is a very rarely used function. I'm sure there are edge cases, but I've never seen it used.

**Comment by floscha** [comment]
I've seen people (including myself) using HDF5 files to store Keras models but I've also never seen anyone using it with pandas or Spark. So probably it makes most sense to leave it out for now and wait until someone requests this feature (if ever).

**Comment by garawalid** [comment]
@thunterdb `pivot_table` sounds a little bit tricky, I'll start with a simple version and we will improve it with different PR. 

Thanks @floscha, @rxin, @athena15 , @thunterdb . I'll update the list as you suggested.

**Comment by garawalid** [comment]
We will ignore `iat` because it needs the position of the row.

**Comment by garawalid** [comment]
I skipped `DataFrame.shift` because we can't union DataFrame of nulls with another one.
