### ISSUE TITLE
Use encapsulation instead of monkey patching / inheritance

### ISSUE THREAD

**Issue by rxin** [databricks/koalas#90]
After spending some time thinking about the issue, I think it would be better for the project to create its own entry point and its own DataFrame / Series class, rather than doing it through monkey patching or inherence to change the existing Spark DataFrame API.

The main reason I am leaning this way now is because Spark and Pandas DataFrames already have quite a few functions with the same name but different semantics, e.g. `sample`, `head`. Keeping existing Spark behavior does not accomplish the goal of the project, while changing existing Spark behavior based on some import statement is an anti-pattern of Python code. Doing it through encapsulation also avoids the issue of Koalas polluting the internal state of Spark's DataFrame through monkey patching.

So here's an alternative design:

koalas: parallel to pandas namespace. Includes I/O functions (`read_csv`, `read_parquet`) as well as general functions (e.g. `concat`, `get_dummies`). Functions here would only work if there is an active SparkSession.

koalas.DataFrame: A completely new interface based on Pandas' DataFrame API. KoalaDataFrame wraps around a Spark DataFrame along with additional internal states.

koalas.Series: Based on Pandas' DataFrame API.

The only thing I'd monkey patch into Spark's DataFrame is a toKoalas method, which turns an existing Spark DataFrame into a Koalas DataFrame.

While this change will bring more code, we will get the following benefits:

- Very clear when users will get the Pandas behavior vs Spark behavior.
- Documentation also becomes clear, as we just provide documentation on Koalas.

The main tradeoff is:

If we go with encapsulation, there is a separate class hierarchy in addition to the existing Spark ones, and the new hierarchy follows strictly Pandas semantics. The downside is that users cannot directly use a Spark DataFrame with Pandas code, and they need to call "spark_ds.toKoalas".

If we go with the current monkey patching approach, it's the opposite of the above. Users can directly use a Spark DataFrame with Pandas code, but existing Spark code's behavior might change as soon as they import koalas package. For example, "head" now returns 5 rows, rather than 1 row. "columns' return a Pandas Index, rather than a Python list. "sample" in the future might also change.

**Comment by AbdealiJK** [comment]
Personally I think inheritance is better than encapsulation because it will help us keep in mind that this should be as similar to pyspark's current functions as possible 

By checking the overridden functions and super() calls, we would be able to immediately figure out which functuonalities are augmented and modified easily. 

I can imagine a case where overriding spark internals could be useful too - and a koala.patch() to patch using this class as the 'default data frame class' would be helpful - if easy to implement.

**Comment by HyukjinKwon** [comment]
It matches to my impression. I learn toward that it's better to have its own entry point. At least, I am 100% sure there would be so many subtleties between Pandas and PySpark as this project grows.

**Comment by dennyglee** [comment]
I  like this approach as the context switching between the Pandas' DataFrame API and the Spark's DataFrame API can be confusing especially when it is common to use both APIs in the same application.  The alternate design would allow clear delineation between Pandas vs./and Spark behavior.

**Comment by johndbritton** [comment]
I'm a fan of encapsulation over monkey patching. The example I can think of is the Rspec package for Ruby. In the early days they would monkey-patch everything and add lots of magic that just worked until there was an unexpected namespace collision which led to lots of debugging issues. They've since moved to a more robust approach where the models that they are enhancing with additional functionality are essentially wrapped by specialized classes to extend them.

**Comment by thunterdb** [comment]
This issue should be closed now.

**Comment by bgweber** [comment]
I'm looking to port an existing Python library to use Koalas in place of Pandas, and pass it DataFrames created from the `toKoalas` method mentioned above. The encapsulation approach seems better for this use case. Are there any open issues on the `toKoalas` implementation?

**Comment by rxin** [comment]
We have switched to the encapsulation approach already, but haven't added the toKoalas method yet. Will add that in the next release.

BTW - should it be more pythonic and called to_koalas, to_ks, or toKoalas?

**Comment by dennyglee** [comment]
Inclined to go with `to_koalas` as its more Pythonic and matches our existing `from_pandas`.

**Comment by thunterdb** [comment]
to_koalas
